### ISSUE TITLE
some questions about modules/specification in uncommonjs

### ISSUE THREAD

**Issue by lifesinger** [kriskowal/uncommonjs#1]
Krisk:

I really appreciate your work, and have some questions about the module specification:

```
2. require must return the same value as module.exports in the identified module, or must throw an exception while trying.
```

In web browsers, sometimes we need to use `require` to load normal unwrapped js or css files. In these cases, throw an exception is annoying to users. In my implementor seajs(http://github.com/seajs/seajs), if error occurs, the `require` will just return `null` instead of throwing an exception. How about do you think this approach?

```
3. require may have a main property.
```

In my opinion, if we want to get the main module exports, we can just use `require('main-module-id')`.  And the `require` only accepts literal string argument, so `require(require.main)` is illegal code. I wonder in which cases we need to use "require.main". Hope you can give me some hints.

```
require must have a resolve function.
```

Why is "must"? I think `resolve` function is only the inner implement code, and it is harmful to expose it to public api. How about change "must" to "may" ?

```
require must have an async function.
```

In FlyScript and SeaJS, we use `module.load` to provide async load. If any error occurs in `require` process, I think return `null` is more robust and friendly for user. In web browsers, sometimes the module file is 404 due to bad network, throw exception in 404 cases will cause all code die. How do you suggest?

```
The module object must have an id property.
```

`module.id` is meaningful in node environment, but in web browsers, the only unique identifier is the `module.uri`. I find to use `module.uri` is concise and helpful to implement memoization logic. Why we must have `module.id` ?

Sorry for my poor english, and very much hope you can answer my doubts. 

Finally, I will do my best to implement an `uncommonjs` module loader in web browsers. My current effort is SeaJS(http://github.com/seajs), I do hope you can review the loader API(http://seajs.com/docs/cheatsheet.html) and give some suggestions. Thanks very much. 

Frank Wang (lifesinger(at)gmail.com)

**Comment by kriskowal** [comment]
On Sat, Jun 4, 2011 at 7:35 AM, lifesinger
reply@reply.github.com
wrote:

> Krisk:
> I really appreciate your work, and have some questions about the module specification:
>    2. require must return the same value as module.exports in the identified module, or must throw an exception while trying.
> In web browsers, sometimes we need to use `require` to load normal unwrapped js or css files. In these cases, throw an exception is annoying to users. In my implementor seajs(http://github.com/seajs/seajs), if error occurs, the `require` will just return `null` instead of throwing an exception. How about do you think this approach?

What's good for users in production is at odds with what is good for
developers while debugging. If a module fails to load, and if that is
module is used, it will cause an error regardless. The only choice we
have is weather to throw an error at the require call (which makes the
problem easy to trace) or throw it the first time somebody
dereferences the exports (in which case the cause is less obvious).  I
stand by the decision to do an early error.

>    3. require may have a main property.
> In my opinion, if we want to get the main module exports, we can just use `require('main-module-id')`.  And the `require` only accepts literal string argument, so `require(require.main)` is illegal code. I wonder in which cases we need to use "require.main". Hope you can give me some hints.

It's a funny edge-case.  The reason for the string-literal requirement
is that we need to be able to scrape the module to find its
dependencies and load them ahead of time. However, require.main
doesn't have to be scraped because it's guaranteed to have been loaded
already axiomatically.  I'm glad you bring this up, because I should
make the exception explicit and I hadn't thought about it.

>    require must have a resolve function.
> Why is "must"? I think `resolve` function is only the inner implement code, and it is harmful to expose it to public api. How about change "must" to "may" ?

I added this because it is helpful for some cases to be able to
resolve identifiers, such as for finding non-module resources. NodeJS
has it. It's trivial to add to other implementations. It isn't useful
if it is not guaranteed to exist across implementations, and is a
hazard if left as a "may" clause.

>    require must have an async function.
> 
> In FlyScript and SeaJS, we use `module.load` to provide async load.

It's a bike shed (an argument about options with no clear difference
in value that consumes too much time and energy from too many people).
I'm going with "require.async". It's what I originally proposed, some
people have implemented, and makes it clear that .async is modifying
the behavior of require. I realize there were many alternate
proposals, and I considered them in the functional specification of
require.async, but I still prefer this name.

> If any error occurs in `require` process, I think return `null` is more robust and friendly for user. In web browsers, sometimes the module file is 404 due to bad network, throw exception in 404 cases will cause all code die. How do you suggest?

Don't leave 404's laying around. They should be eliminated in
development, and if they exist in production, your page is hosed
anyway. The null will only delay the problem.

>    The module object must have an id property.
> `module.id` is meaningful in node environment, but in web browsers, the only unique identifier is the `module.uri`. I find to use `module.uri` is concise and helpful to implement memoization logic. Why we must have `module.id` ?

The idea with module.id is for it to be consistent across runs, after
moving files, and even across engines, while module.path (which in
this spec is a URI, even if it is just a relative file URI) is more
useful as a debugging name or a name to fetch neighboring resources.
Node of course breaks this, which I think is anti-social but I can't
do much about that.  If you're using URIs as the canonical identifier
in a system of modules, instead of its package-relative identifier,
you probably ought to follow Node and use the URI as the ID, but I
have different ideas about what "id" means, so I won't be going that
direction myself.

> Sorry for my poor english, and very much hope you can answer my doubts.
> 
> Finally, I will do my best to implement an `uncommonjs` module loader in web browsers. My current effort is SeaJS(http://github.com/seajs), I do hope you can review the loader API(http://seajs.com/docs/cheatsheet.html) and give some suggestions. Thanks very much.

Thanks for your feedback and support. Your English is fine.

Kris Kowal

**Comment by lifesinger** [comment]
Krisk:

Thanks very much for your quick response. I will make some changes to let
SeaJS meet uncommonjs module specification.

Best regards.

Frank Wang

On Sun, Jun 5, 2011 at 10:50 AM, kriskowal <
reply@reply.github.com>wrote:

> On Sat, Jun 4, 2011 at 7:35 AM, lifesinger
> reply@reply.github.com
> wrote:
> 
> > Krisk:
> > I really appreciate your work, and have some questions about the module
> > specification:
> > 1. require must return the same value as module.exports in the
> >    identified module, or must throw an exception while trying.
> >    In web browsers, sometimes we need to use `require` to load normal
> >    unwrapped js or css files. In these cases, throw an exception is annoying to
> >    users. In my implementor seajs(http://github.com/seajs/seajs), if error
> >    occurs, the `require` will just return `null` instead of throwing an
> >    exception. How about do you think this approach?
> 
> What's good for users in production is at odds with what is good for
> developers while debugging. If a module fails to load, and if that is
> module is used, it will cause an error regardless. The only choice we
> have is weather to throw an error at the require call (which makes the
> problem easy to trace) or throw it the first time somebody
> dereferences the exports (in which case the cause is less obvious).  I
> stand by the decision to do an early error.
> 
> > 1. require may have a main property.
> >    In my opinion, if we want to get the main module exports, we can just use
> >    `require('main-module-id')`.  And the `require` only accepts literal string
> >    argument, so `require(require.main)` is illegal code. I wonder in which
> >    cases we need to use "require.main". Hope you can give me some hints.
> 
> It's a funny edge-case.  The reason for the string-literal requirement
> is that we need to be able to scrape the module to find its
> dependencies and load them ahead of time. However, require.main
> doesn't have to be scraped because it's guaranteed to have been loaded
> already axiomatically.  I'm glad you bring this up, because I should
> make the exception explicit and I hadn't thought about it.
> 
> >    require must have a resolve function.
> > Why is "must"? I think `resolve` function is only the inner implement
> > code, and it is harmful to expose it to public api. How about change "must"
> > to "may" ?
> 
> I added this because it is helpful for some cases to be able to
> resolve identifiers, such as for finding non-module resources. NodeJS
> has it. It's trivial to add to other implementations. It isn't useful
> if it is not guaranteed to exist across implementations, and is a
> hazard if left as a "may" clause.
> 
> >    require must have an async function.
> > 
> > In FlyScript and SeaJS, we use `module.load` to provide async load.
> 
> It's a bike shed (an argument about options with no clear difference
> in value that consumes too much time and energy from too many people).
> I'm going with "require.async". It's what I originally proposed, some
> people have implemented, and makes it clear that .async is modifying
> the behavior of require. I realize there were many alternate
> proposals, and I considered them in the functional specification of
> require.async, but I still prefer this name.
> 
> > If any error occurs in `require` process, I think return `null` is more
> > robust and friendly for user. In web browsers, sometimes the module file is
> > 404 due to bad network, throw exception in 404 cases will cause all code
> > die. How do you suggest?
> 
> Don't leave 404's laying around. They should be eliminated in
> development, and if they exist in production, your page is hosed
> anyway. The null will only delay the problem.
> 
> >    The module object must have an id property.
> > `module.id` is meaningful in node environment, but in web browsers, the
> > only unique identifier is the `module.uri`. I find to use `module.uri` is
> > concise and helpful to implement memoization logic. Why we must have `
> > module.id` ?
> 
> The idea with module.id is for it to be consistent across runs, after
> moving files, and even across engines, while module.path (which in
> this spec is a URI, even if it is just a relative file URI) is more
> useful as a debugging name or a name to fetch neighboring resources.
> Node of course breaks this, which I think is anti-social but I can't
> do much about that.  If you're using URIs as the canonical identifier
> in a system of modules, instead of its package-relative identifier,
> you probably ought to follow Node and use the URI as the ID, but I
> have different ideas about what "id" means, so I won't be going that
> direction myself.
> 
> > Sorry for my poor english, and very much hope you can answer my doubts.
> > 
> > Finally, I will do my best to implement an `uncommonjs` module loader in
> > web browsers. My current effort is SeaJS(http://github.com/seajs), I do
> > hope you can review the loader API(http://seajs.com/docs/cheatsheet.html)
> > and give some suggestions. Thanks very much.
> 
> Thanks for your feedback and support. Your English is fine.
> 
> Kris Kowal
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kriskowal/uncommonjs/issues/1#comment_1303345

## 

O / ɧB]gJ^
eH⦳E
http://lifesinger.org/

**Comment by lifesinger** [comment]
I'd like to add you to my professional network on LinkedIn.
- lifesinger

lifesinger wang
Web Developer at Taobao.com
China

Confirm that you know lifesinger wang:
https://www.linkedin.com/e/s5d15n-gsbgxz3n-44/isd/4129329550/QSUvF2cz/?hs=false&tok=3hvv0LPWGlyAU1

## 

You are receiving Invitation to Connect emails. Click to unsubscribe:
http://www.linkedin.com/e/s5d15n-gsbgxz3n-44/ApXI6k7-gitN3c6c0VCdeB1_fCGbU98DAMCITs6_XzCDUPkDTD2mPy2bX2h_0NhxPEAoUj2xN8tB5TIBTQ6rPKnRgMIc3Aq_WR07rlk/goo/reply%2Bi-1002776-54f8457f099fddd241846c45c1cf23b0eca63f5e%40reply%2Egithub%2Ecom/20061/I1424882623_1/?hs=false&tok=10FjB6w4alyAU1

(c) 2011 LinkedIn Corporation. 2029 Stierlin Ct, Mountain View, CA 94043, USA.
