### ISSUE TITLE
Promises: more than just `then`?

### ISSUE THREAD

**Issue by domenic** [kriskowal/uncommonjs#2]
I'm trying to really start using promises in a way that conforms to some kind of standard. The only thing the various standards and implementations seem to agree on is a `then` method, but I find methods for unconditional callbacks (jQuery's `always` or Q's `fin`), and for errors in particular (jQuery or Q's `fail`) to be quite useful.

Is there any hope of getting such methods into the UncommonJS promises spec?

**Comment by kriskowal** [comment]
Yeah, though I don't know who else is tracking UncommonJS/Promises so it might be a bust. I am working with MarkM; his current proposal looks like http://wiki.ecmascript.org/doku.php?id=strawman:concurrency and my current proposal looks like Q's API. Just need to convert it into specese.

**Comment by domenic** [comment]
This was my sixth-ever opened GitHub issue ^_^
