### ISSUE TITLE
Revive

### ISSUE THREAD

**Issue by cadorn** [kriskowal/uncommonjs#4]
I am in the process of cleaning up all my portable JS modules/packages/programs work and am looking for a home for the specifications.

My goal is to have tests for each specification and provide examples that run on various JS engines/platforms/ecosystems/frameworks. The idea is to develop a minimal core set of specs and then a list of optional layers on top and how to use these in the wild. Ideally this would become the definitive reference of how to write portable JS applications and components composed of packages and modules.

Most importantly I am looking for someone interested in reviewing and helping in building a community around these specs. Your experience with https://github.com/montagejs/mr would be invaluable in this process. Would you be interested in making `mr` comply to the specs we would be defining?

I would start by cloning this repo and building a NodeJS-based site that pulls in the specs and support files and provides a good user experience to explore `uncommonjs`.

I have started implementing package and module parsing libraries that can shim differences between communities:
- https://github.com/pinf-it/pinf-it-package-insight
- https://github.com/pinf-it/pinf-it-module-insight

Which I am using to generate portable JS bundles:
- https://github.com/pinf-it/pinf-it-bundler

Loadable by a minimal JS loader that provides sovereign namespaces for each package:
- https://github.com/pinf/pinf-loader-js

I am wrapping the loader for various communities starting with:
- https://github.com/pinf/pinf-for-nodejs
- https://github.com/pinf/pinf-for-requirejs

We would be able to use these projects to automatically test all the specifications against the various communities to ensure interoperability.

What do you think? Where do you see commonjs/uncommonjs or JS portable applications going in general?

**Comment by kriskowal** [comment]
Sorry for the late reply. I would love to work with you on convergent implementations again, but I don’t personally have the mindshare to spare. Perhaps between @stuk, maintainer of Mr, and me we can highlight whatever points we could converge on.

**Comment by kriskowal** [comment]
@cadorn, I’m granting you collaborator rights on this repo. I still need to read your articles.

**Comment by cadorn** [comment]
@kriskowal That is great to hear! I was taking the lack of response as an indicator of there not being interest but I guess I jumped the gun.

@kriskowal @stuk Please hold off on studying my projects for a bit. I included that more as a roadmap. I am making steady progress and should have something much more substancial in the coming weeks/months (depending on how much the sun shines :))

If you are interested at looking at the foundation of my work you can study the JS loader (https://github.com/pinf/pinf-loader-js). All my projects revolve either around feeding bundles into the loader or building tooling an intelligence for apps on top of the loader.

I will start my own fork of uncommonjs and start the work on a better UI and user site.
